### ISSUE TITLE
Stringing and Oozing with AK-Neo-PLA-0.2mm

### ISSUE THREAD

**Issue by angeloken** [sclebo05/KobraNeoProfiles#13]
i got stringing and oozing when i use the profile. i already try using retraction tower for calibration but no improvement, any suggestion how to adjust it?, because  from what i heard that direct driver use retraction distance 1mm and bowden 6mm, but using 1mm give me stringing and oozing result

**Comment by rbq** [comment]
I'm using the included white Anycubic PLA and had to reduce the temperature to 185° C to print anything but spiderwebs.

**Comment by jokubasver** [comment]
Branching (a bit different from stringing) was the main problem I've been battling ever since I got the printer, even when running Klipper. Tried many things - e-step calibration, replacing the hotend, different temperatures, higher retraction distance, etc etc. What helped for me mainly was reducing retraction speed down to 25mm/s, while keeping the retraction distance at 1mm. Also making sure that the nozzle is flush against the heatbrake, tuning input shaping and pressure advance on Klipper, reducing flow in slicer to 97%, but these things didn't have as much of an impact ad slowing down retraction.

**Comment by sclebo05** [comment]
I have better luck with 50mm/s retraction speed, 2mm.  

Last week, my AC died, and my many rolls of filament were subjected to high humidity for a week. So stringing is a new issue for me, never had issues before, so found this thread timely.  Thanks for the above input from everyone.  @angeloken Maybe try retraction distance and speed tweaks, and alternate temps?

**Comment by sclebo05** [comment]
No updates for a month, hoping he resolved his stringing.
