### ISSUE TITLE
Errors in gcode

### ISSUE THREAD

**Issue by viruz82** [sclebo05/KobraNeoProfiles#9]
`echo:Unknown command: "M117 Homing X/Y ..."
echo:Unknown command: "M117 Homing Z ..."
echo:Unknown command: "M117 Heating ..."
echo:Unknown command: "M117 Start cleaning ..."`

M117 has to be M118. :)

**Comment by sclebo05** [comment]
Any more info on your setup? I'm running through Octoprint with a few plugins, into a recompiled firmware based on 1.3.3.

**Comment by viruz82** [comment]
Sorry. I'm on the original 1.3.3 firmware and saw the errors in Pronterface. After changing M117 to M118 everything was fine.

**Comment by sclebo05** [comment]
Let me do some testing on bare metal, I'm not sure there's a downside to putting both commands in one after the other. I'll respond when I know more, thanks for the information

**Comment by TheUnlimited64** [comment]
Im not having issues with M117, running 1.3.3 and Cura with Octoprint:
Send: N13 M117 Heating ...*96
Recv: ok

**Comment by sclebo05** [comment]
Which slice are you using? Maybe this is slicer specific

**Comment by TheUnlimited64** [comment]
You mean Cura? I use Cura 5.3.0
But I think it's not slicer specific, because I think it only appends the gcode at the start/beginning

**Comment by Xgl0baltk** [comment]
Just my 2 Cents, Repetier Server also doesn't have a problem with M117, yet depends on where you want the message, M117 appears in Serial and the display and gets an OK from the printer, M118 is only a serial message.. 

Though regarding the Gcode - in all that long preparation, i don't see G29 Auto Bed Level anywhere for example, and G28 - each home is separate with a message in between that it is now homing Z.. really necessary? -

But just wanted to throw this in because i saw the thread and i'm getting my Neo tomorrow.

**Comment by sclebo05** [comment]
> But just wanted to throw this in because i saw the thread and i'm getting my Neo tomorrow.

How's your Neo performing?  

G29 performs the auto level - something you probably do once in a while, certainly not with each print. 

Full disclosure, I'm running my firmware that 'unlocks' some of the messaging that Anycubic disabled (e.g. M117) and I use Octoprint as my go between Prusa and my printer.

I've seen references to other servers, such at Repetier or Pronterface - users at this level can certainly make the small adjustments needed, so I won't chase those.

My target audience for the gcodes is the new user who isn't getting the Intro line with each print, and may not know how to call in the bed mesh.  Otherwise, use them as a template, and hack away for your setup!
